# Splunk Connect for SNMP Traps
# Sample Configuration file
snmp:
  port: 2062
  ipv4: True
  ipv6: False
  communities:
    v1:
      - public
      - "my-area"
  mibs:
    url:
      - "file:///usr/share/snmp/mibs"
      - "http://mibs.snmplabs.com/asn1/@mib@"
      # - "http://localhost:8070/asn1/@mib@"
    load_list:  
      - "SNMPv2-MIB"
      - "SNMP-COMMUNITY-MIB"
      - "SNMPv2-CONF"
      - "A10-COMMON-MIB"
      - "A3COM-HUAWEI-BLG-MIB"
      - "NET-SNMP-EXAMPLES-MIB"
hec:
  protocol: https
  host: 127.0.0.1
  port: 8088
  endpoint: /services/collector/event
  authentication_token: <hec token>
thread-pool:
  max-suggested-working-threads: 10
