# Splunk Connect for SNMP Traps
# Sample Configuration file
snmp:
  port: 2062
  ipv4: True
  ipv6: False
  communities:
    v1:
      - public
      - "my-area"
hec:
  protocol: https
  host: 127.0.0.1
  port: 8088
  endpoint: /services/collector/event
  authentication_token: 1f1a82b3-8bfd-43d4-9a20-98fdee4c95b9
thread-pool:
  max-suggested-working-threads: 10
