# Splunk Connect for SNMP Traps
# Sample Configuration file
snmp:
  communities:
    v1:
      - public
      - "my-area"
  mib-server:
    # This is need to be mapped with k8s
    url: "http://mib-server:5000"
    # url: "http://localhost:5000"
thread-pool:
  max-suggested-working-threads: 10