# Splunk Connect for SNMP Traps
# Sample Configuration file
snmp:
  communities:
    v1:
      - public
      - "my-area"
  mibs:
    url:
      - "file:///usr/share/snmp/mibs"
      # *TODO*: Replace below URL with MIB Server's URL returned during service discovery. 
      - "http://mibs.thola.io/asn1/@mib@"
    load_list: "lookups/sample_mibs_list.csv"
thread-pool:
  max-suggested-working-threads: 10

