# Splunk Connect for SNMP Traps
# Sample Configuration file
snmp:
  port: 2162
  ipv4: True
  ipv6: True
  communities:
    v1:
      - public
      - "my-area"
thread-pool:
  max-suggested-working-threads: 10
