# Splunk Connect for SNMP Traps
# Sample Configuration file
snmp:
  port: 2162
  ipv4: True
  ipv6: True
  communities:
    v1:
      - public
      - "my-area"
  mibs:
    url:
      # - "file:///usr/share/snmp/mibs"
      # *TODO*: Replace below URL with MIB Server's URL returned during service discovery. 
      - "http://mibs.thola.io/asn1/@mib@"
    load_list:  
      - "SNMPv2-MIB"
      - "SNMP-COMMUNITY-MIB"
      - "SNMPv2-CONF"
      - "NET-SNMP-EXAMPLES-MIB"
thread-pool:
  max-suggested-working-threads: 10
