# Splunk Connect for SNMP Traps
# Sample Configuration file
snmp:
  port: 2062
  ipv4: True
  ipv6: False
  communities:
    v1:
      - public
      - "my-area"
  mibs:
    url:
      - "file:///usr/share/snmp/mibs"
      - "http://mibs.snmplabs.com/asn1/@mib@"
hec:
  protocol: https
  host: 127.0.0.1
  port: 8088
  endpoint: /services/collector/event
  authentication_token: <hec token>
thread-pool:
  max-suggested-working-threads: 10